name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '18.x'
    - name: load env variables
       env:
           DB_HOST: ${{ secrets.DB_HOST }}
           DB_USER: ${{ secrets.DB_USER }}
           DB_PASS: ${{ secrets.DB_PASS }}    
    - name: Run Prisma query
      run: npx prisma query

    - name: Install dependencies
      run: npm install

    - name: Run tests with coverage
      run: |
        npm run test
        npm run coverage
