name: Node.js CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  setup-db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Run Prisma migrate dev
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/mydatabase
        run: npx prisma migrate dev --name init --create-db

      - name: Run tests with coverage
        run: |
          npm run test
          npm run coverage
